import type { BruddenProduct, AgroforestaProduct } from "./types"

export const bruddenProducts: BruddenProduct[] = [
  {
    name: "Atomizador",
    model: "ATB-18",
    priceMayorista: 3992.0,
    pricePublico: 4990.0,
    minCompra: "10 Unidades Mix",
     image: "/images/atomizador.jpg",
  },
  {
    name: "Pulverizador de mochila motorizado",
    model: "BS-500",
    priceMayorista: 3992.0,
    pricePublico: 4990.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Pulverizador-de-mochila-motorizado.jpg", 
  },
  {
    name: "Desmalezadora",
    model: "BR-45",
    priceMayorista: 3992.0,
    pricePublico: 4990.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Desmalezadora.jpg",

  },
  {
    name: "Podadora de altura telescópica",
    model: "PB-26",
    priceMayorista: 4940.0,
    pricePublico: 5500.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Podadora-de-altura-telescópica.jpg",
  },
  {
    name: "Pulverizador estacionario",
    model: "BS-300",
    priceMayorista: 4400.0,
    pricePublico: 5500.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Pulverizador-estacionario.jpg",
  },
  {
    name: "Multifuncional",
    model: "BMU-260 G2",
    priceMayorista: 4350.0,
    pricePublico: 4900.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Multifuncional.jpg",
  },
  {
    name: 'Motosierra 16"',
    model: "MB-380",
    priceMayorista: 1760.0,
    pricePublico: 2500.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Motosierra-16.jpg",
  },
  {
    name: 'Motosierra 20"',
    model: "MB-260",
    priceMayorista: 2990.0,
    pricePublico: 3900.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Hoyadora",
    model: "K-52 P",
    priceMayorista: 3859.0,
    pricePublico: 4820.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Hoyadora.jpg",
  },
  {
    name: "Barreno 300 MM",
    model: "300 MM",
    priceMayorista: 1080.0,
    pricePublico: 1350.0,
    minCompra: "4 Unidades",
    image: "/images/Barreno-300-MM.jpg",
  },
  {
    name: "Barreno 250 MM",
    model: "250 MM",
    priceMayorista: 1000.0,
    pricePublico: 1250.0,
    minCompra: "4 Unidades",
  },
  {
    name: "Barreno 150 MM",
    model: "150 MM",
    priceMayorista: 950.0,
    pricePublico: 1150.0,
    minCompra: "4 Unidades",
  },
  {
    name: "Barreno 100 MM",
    model: "100 MM",
    priceMayorista: 880.0,
    pricePublico: 1100.0,
    minCompra: "4 Unidades",
  },
  {
    name: "Cortacésped CG620-T4 Motor Subaru",
    model: "CG620-T4",
    priceMayorista: 4680.0,
    pricePublico: 5200.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Cortacésped-CG620-T4.jpg",
  },
  {
    name: "Cortacésped CG620-T4T Motor Subaru",
    model: "CG620-T4T",
    priceMayorista: 5085.0,
    pricePublico: 5650.0,
    minCompra: "10 Unidades Mix",
    description: "Sistema de tracción en las ruedas traseras",
  },
  {
    name: "Derribadora selectiva de cosecha",
    model: "DSC-18",
    priceMayorista: 6210.0,
    pricePublico: 6900.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Derribadora-selectiva-de-cosecha.jpg"
,
  },
  {
    name: "Motobomba",
    model: "K-43M",
    priceMayorista: 2560.0,
    pricePublico: 3200.0,
    minCompra: "10 Unidades Mix",
    image: "/images/Motobomba.jpg",
  },
  {
    name: "Pulverizador",
    model: "S-16",
    priceMayorista: 385.0,
    pricePublico: 515.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Pulverizador",
    model: "S-20",
    priceMayorista: 425.0,
    pricePublico: 575.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Pulverizador Costal a batería",
    model: "PB-20B",
    priceMayorista: 1808.0,
    pricePublico: 2260.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Sopladora de mochila",
    model: "SB-630",
    priceMayorista: 3919.2,
    pricePublico: 4899.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Cortasetos",
    model: "BCV-260",
    priceMayorista: 2879.2,
    pricePublico: 3599.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Desmalezadora",
    model: "T-26",
    priceMayorista: 2150.0,
    pricePublico: 2900.0,
    minCompra: "10 Unidades Mix",
  },
  {
    name: "Atomizador Eléctrico",
    model: "1.5 litros",
    priceMayorista: 280.0,
    pricePublico: 325.0,
    minCompra: "4 Unidades",
  },
  {
    name: "Desmalezadora",
    model: "BC-35",
    priceMayorista: 3200.0,
    pricePublico: 3998.0,
    minCompra: "4 Unidades",
  },
]

export const agroforestaProducts: AgroforestaProduct[] = [
  {
    name: "Green Garden Universal",
    precioPublico: 89.5,
    precioMinorista: 65.0,
    precioMayorista: 60.0,
    precioContado: 58.0,
    unidadesCaja: 12,
  },
  {
    name: "Happy Plant Floración",
    precioPublico: 77.8,
    precioMinorista: 55.0,
    precioMayorista: 50.0,
    precioContado: 48.0,
    unidadesCaja: 12,
  },
  {
    name: "Happy Plant Multivitamínico Forte",
    precioPublico: 89.5,
    precioMinorista: 65.0,
    precioMayorista: 60.0,
    precioContado: 58.0,
    unidadesCaja: 12,
  },
  {
    name: "Happy Plant Reverdesciente",
    precioPublico: 77.8,
    precioMinorista: 55.0,
    precioMayorista: 50.0,
    precioContado: 48.0,
    unidadesCaja: 12,
  },
  {
    name: "Green Garden Orquídeas",
    precioPublico: 89.5,
    precioMinorista: 65.0,
    precioMayorista: 60.0,
    precioContado: 58.0,
    unidadesCaja: 12,
  },
  {
    name: "Green Garden Hidropónica Mayor I",
    precioPublico: 83.65,
    precioMinorista: 60.0,
    precioMayorista: 55.0,
    precioContado: 53.0,
    unidadesCaja: 12,
  },
  {
    name: "Happy Plant Abrillantador de Hojas",
    precioPublico: 89.9,
    precioMinorista: 65.0,
    precioMayorista: 60.0,
    precioContado: 57.0,
    unidadesCaja: 12,
  },
  {
    name: "Lenta Liberación 14-14-14",
    precioPublico: 72.5,
    precioMinorista: 51.0,
    precioMayorista: 47.0,
    precioContado: 45.0,
    unidadesCaja: 50,
    description:
      "Se pueden despachar cajas mixtas a partir de cliente mayorista, con los cual se ajustarán precios de productos.",
  },
]

